name: build

on:
  pull_request:
    branches:
      - main
      - dev
  push:
    branches:
      - dev

jobs:
  debug-build:
    runs-on: self-hosted
    container:
      image: mingc/android-build-box:latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 1

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: "corretto"
          java-version: "21"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          cache-read-only: ${{ github.event_name == 'pull_request' || (github.ref != 'refs/heads/main' && github.ref != 'refs/heads/dev' && github.ref_type != 'tag') }}

      - name: Assemble Foss Debug
        run: ./gradlew assembleFossDebug

      - name: Assemble Play Debug
        run: ./gradlew assemblePlayDebug
