name: release

on:
  push:
    tags:
      - "v*"

jobs:
  release-build:
    runs-on: self-hosted
    container:
      image: mingc/android-build-box:latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: "corretto"
          java-version: "21"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Decode Keystore
        run: |
          echo "$SIGNING_KEYSTORE_BASE64" | base64 -di > "${{ runner.temp }}/keystore.jks"
        env:
          SIGNING_KEYSTORE_BASE64: ${{ secrets.SIGNING_KEYSTORE_BASE64 }}

      - name: Configure keystore.properties
        run: |
          echo "storePassword=${{ secrets.KEYSTORE_STORE_PASSWORD }}" >> keystore.properties
          echo "keyPassword=${{ secrets.KEYSTORE_KEY_PASSWORD }}" >> keystore.properties
          echo "keyAlias=${{ secrets.KEYSTORE_KEY_ALIAS }}" >> keystore.properties
          echo "storeFile=${{ runner.temp }}/keystore.jks" >> keystore.properties

      - name: Create temp folder
        run: mkdir -p ${{ runner.temp }}/release

      - name: Clean before Foss build
        run: ./gradlew clean

      - name: Build Foss Release APK
        run: ./gradlew assembleFossRelease

      - name: Copy Foss APK artifact
        run: cp app/build/outputs/apk/foss/release/app-foss-release.apk "${{ runner.temp }}/release/app-foss-release.apk"

      - name: Clean before Play build
        run: ./gradlew clean

      - name: Build Play Release APK
        run: ./gradlew assemblePlayRelease

      - name: Copy Play APK artifact
        run: cp app/build/outputs/apk/play/release/app-play-release.apk "${{ runner.temp }}/release/app-play-release.apk"

      - name: Build Play Release AAB
        run: ./gradlew bundlePlayRelease

      - name: Upload Foss Release APK (Artifact)
        uses: actions/upload-artifact@v3
        with:
          name: foss-release-apk
          path: ${{ runner.temp }}/release/app-foss-release.apk

      - name: Upload Play Release APK (Artifact)
        uses: actions/upload-artifact@v3
        with:
          name: play-release-apk
          path: ${{ runner.temp }}/release/app-play-release.apk

      - name: Upload Release Assets to Forgejo Release
        uses: actions/forgejo-release@v2.11.3
        with:
          direction: upload
          release-dir: ${{ runner.temp }}/release
          release-notes-assistant: true

      - name: Upload to Google Play
        uses: https://github.com/r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}
          packageName: de.hbch.traewelling
          releaseFiles: app/build/outputs/bundle/playRelease/app-play-release.aab